version: '3.9'
services:
  mysql:
    profiles:
      - middleware
    image: mysql:8-debian
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: develop
      MYSQL_PASSWORD: develop
      MYSQL_DATABASE: develop
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - ${HOST_MYSQL_PORT:-3306}:3306

  postgres:
    profiles:
      - middleware
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${HOST_POSTGRES_PORT:-5432}:5432
